### ISSUE TITLE
I cannot run the era_test_node  command and prompts the error 'xxxxx' on my server

### ISSUE THREAD

**Issue by crazytang** [matter-labs/era-test-node#172]
#### 📝 Description

I ran the command
```shell
era_test_node fork testnet
``` 
and I got the error
``` shell
thread 'main' panicked at 'Could not find block #12557044 (0xed782a8be6382299e84178fe5b5ef39582091c5db1a6291bb7c8bee142c72114) in "https://testnet.era.zksync.dev:443"', src/fork.rs:295:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

#### 🖥️ Environment

- **Rust version**: rustc 1.72.0 (5680fa18f 2023-08-23)
- **Operating System & Version**: Ubuntu 22.04.2 LTS
- **Other relevant environment details**:
- **era_test_node version**: I downloaded the latest version "[era-test-node-v0.1.0-alpha.6-x86_64-unknown-linux-gnu.tar.gz](https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.6/era_test_node-v0.1.0-alpha.6-x86_64-unknown-linux-gnu.tar.gz)", but it shows version is "era_test_node 0.1.0-alpha.5"

**Comment by crazytang** [comment]
After I recompiled the source code, the error disappeared

**Comment by nbaztec** [comment]
This issue is caused by https://github.com/matter-labs/zksync-era/pull/167 updating the transaction `chainId` type, which is not being decoded properly. Should be fixed once we update the upstream dependencies.

**Comment by zjpetersen** [comment]
Hi I'm still getting this issue in v0.1.0-alpha.7

I tried with both testnet and mainnet and also tried using an older branche (--fork-at 13000000 on mainnet)
