### ISSUE TITLE
Replay tx failing due to L2 gas change in mainnet

### ISSUE THREAD

**Issue by mm-zk** [matter-labs/era-test-node#246]
#### 📝 Description

Replay tx is failing, as the mainnet request was using a lower gas fee.

In mainnet, since boojum launch, we are slowly lowering the l2 gas price. (pre-boojum was 0.25 Gwei - now AFAIK it dropped to 0.23 and now 0.19). Unfortunately in era-test-node, we still depend on the hardcoded value of 0.25 Gwei (L2_GAS_PRICE).

This results in the error below, when trying to replay a fresh transaction.

The proper solution - in case of replaying a transaction - would be to load the l2 gas fee information from the fork.

#### 🔄 Reproduction Steps

```
cargo run -- --show-storage-logs=all --show-vm-details=all --show-gas-details=all replay_tx mainnet 0xb0f917b869172db5123e7a63bc0f9ef4fa7498f1db34d094250087578136fde6
```

#### 🤔 Expected Behavior

Replay transaction 

#### 😯 Current Behavior

Submitted Tx is Unexecutable 0xb0f917b869172db5123e7a63bc0f9ef4fa7498f1db34d094250087578136fde6 because of MaxFeePerGasTooLow 190000000

**Comment by mm-zk** [comment]
FYI - the current workaround is to lower the 
```
pub const L2_GAS_PRICE: u64 = 190_000_000;
```

**Comment by githubdoramon** [comment]
Maybe related, but if not,happy to create a new issue

> era_test_node returns a base fee of zero when getting latest block via eth_getBlockByNumber. If I try to submit a tx with such a fee it will produce an error block base fee higher than max fee per gas. Tx goes through if I use a base fee of 0.25 gwei

**Comment by dutterbutter** [comment]
Fixed in https://github.com/matter-labs/era-test-node/releases/tag/v0.1.0-alpha.17

**Comment by MexicanAce** [comment]
Reopening as this is still an issue, since price can be changed at any time

**Comment by dutterbutter** [comment]
Closing due recent release in `alpha.19`
